---
kind: pipeline
name: windows-2004

platform:
  os: windows
  arch: amd64
  version: 2004

clone:
  disable: true

steps:
  - name: clone
    image: luthermonson/drone-git:windows-2004-amd64
  - name: build
    pull: default
    image: rancher/dapper:v0.5.3
    commands:
      - dapper.exe -f Dockerfile.dapper ci
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine

  - name: stage-binaries
    image: maiwj/dapper:windows-1809
    commands:
      - "Get-ChildItem -Path ./bin; Copy-Item -Force -Path ./bin/wins.exe -Destination ./package/; Get-ChildItem -Path ./package/"

  - name: github_binary_release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files:
        - bin/wins.exe
    when:
      instance:
        - drone-publish.rancher.io
      ref:
        - refs/head/master
        - refs/tags/*
      event:
        - tag

volumes:
  - name: docker_pipe
    host:
      path: \\\\.\\pipe\\docker_engine
