name: Pull Request

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  # While golanglint-ci is also run in the mage file,
  # adding an explicit gha step highlights the syntax errors
  # when reviewing PRs
  golint:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6.1.0
        with:
          args: --timeout=10m
          version: v1.59

  test:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-2019, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'
    
    - name: Install Dependencies
      run: |
        go install github.com/magefile/mage@v1.15.0
        go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.55.2

    - name: Run E2E tests
      shell: pwsh
      run: |
        Install-Module -Name DockerMsftProvider -Force
        Import-Module -Name HostNetworkingService
        set PSModulePath=&&powershell -command "mage TestAll"
